-- Création de la BDD
CREATE DATABASE IF NOT EXISTS ci_cd CHARSET utf8mb4;
USE ci_cd;

CREATE TABLE IF NOT EXISTS users(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
`password` VARCHAR(100) NOT NULL,
roles VARCHAR(100) DEFAULT 'ROLE_USER' NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS book(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(50) NOT NULL,
`description` VARCHAR(255) NOT NULL,
publish_at DATE NOT NULL,
cover VARCHAR(255),
author VARCHAR(100) NOT NULL,
available BOOLEAN DEFAULT true NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS category(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`name` VARCHAR(50) UNIQUE NOT NULL 
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS lending(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
lend_at DATETIME NOT NULL,
return_at DATETIME NOT NULL,
mandatory_at DATE NOT NULL,
book_id INT NOT NULL,
user_id INT NOT NULL,
CONSTRAINT fk_lend_users 
FOREIGN KEY (user_id) 
REFERENCES users(id)
ON DELETE CASCADE,
CONSTRAINT fk_add_book
FOREIGN KEY (book_id)
REFERENCES book(id)
ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS book_category(
book_id INT,
category_id INT,
PRIMARY KEY(book_id, category_id),
CONSTRAINT fk_completed_book
FOREIGN KEY(book_id)
REFERENCES book(id),
CONSTRAINT fk_completed_category
FOREIGN KEY(category_id)
REFERENCES category(id)
)ENGINE=InnoDB;
