# nom
name: e2e tests cypress et PHP
# declencheur
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature
      - main
# environnement
jobs:
  build:
    # image unbuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout recuperation du code
        uses: actions/checkout@v6
    

# job : build (environnemt du projet)
# etape : checkout code
# compiler le code

# job : test (environnement du projet)
# installer cypress
# lancer les tests cypress

